Fix Handle possible JSONDecode Error #37
Code-For-Chicago/greater-chicago-food-despository pull request #41
Opened 2021-04-24 00:07 UTC by brickman1444

2021-04-24 15:38 UTC, michaelpkuhn approved these changes

2021-04-24 15:39 UTC, michaelpkuhn requested changes
Changing to request changes

Thought github would block due to failed checks. Once those pass, can reapprove

2021-04-24 20:14 UTC, brickman1444 commented
@michaelpkuhn should be good to go now

2021-04-27 17:58 UTC, michaelpkuhn approved these changes

2021-04-29 03:15 UTC, merged